Assuming unrestricted shared filesystem usage.
None
host: Nicolass-MacBook-Pro-2.local
Building DAG of jobs...
Your conda installation is not configured to use strict channel priorities. This is however important for having robust and correct environments (for details, see https://conda-forge.org/docs/user/tipsandtricks.html). Please consider to configure strict priorities by executing 'conda config --set channel_priority strict'.
Creating conda environment envs/nextstrain_env.yaml...
Downloading and installing remote packages.
CreateCondaEnvironmentException:
Could not create conda environment from /Users/Carlos/Desktop/Bedford/esm-selection/envs/nextstrain_env.yaml:
Command:
conda env create --quiet --no-default-packages --file "/Users/Carlos/Desktop/Bedford/esm-selection/.snakemake/conda/ec57a56ea5bc92db3e694d1da51e296d_.yaml" --prefix "/Users/Carlos/Desktop/Bedford/esm-selection/.snakemake/conda/ec57a56ea5bc92db3e694d1da51e296d_"
Output:
Channels:
 - conda-forge
 - bioconda
 - defaults
Platform: osx-arm64
Collecting package metadata (repodata.json): ...working... Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x10469b590>: Failed to resolve 'repo.anaconda.com' ([Errno 8] nodename nor servname provided, or not known)")': /pkgs/main/osx-arm64/repodata.json.zst

Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x104699370>: Failed to resolve 'repo.anaconda.com' ([Errno 8] nodename nor servname provided, or not known)")': /pkgs/main/noarch/repodata.json.zst

Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x10469aa80>: Failed to resolve 'repo.anaconda.com' ([Errno 8] nodename nor servname provided, or not known)")': /pkgs/r/noarch/repodata.json.zst

Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x1046bc0e0>: Failed to resolve 'repo.anaconda.com' ([Errno 8] nodename nor servname provided, or not known)")': /pkgs/r/osx-arm64/repodata.json.zst

Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x1046bd190>: Failed to resolve 'repo.anaconda.com' ([Errno 8] nodename nor servname provided, or not known)")': /pkgs/main/noarch/repodata.json.zst

Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x1046bd280>: Failed to resolve 'repo.anaconda.com' ([Errno 8] nodename nor servname provided, or not known)")': /pkgs/r/noarch/repodata.json.zst

Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x1046bd010>: Failed to resolve 'repo.anaconda.com' ([Errno 8] nodename nor servname provided, or not known)")': /pkgs/main/osx-arm64/repodata.json.zst

Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x1046bd580>: Failed to resolve 'repo.anaconda.com' ([Errno 8] nodename nor servname provided, or not known)")': /pkgs/r/osx-arm64/repodata.json.zst

Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x1046becc0>: Failed to resolve 'repo.anaconda.com' ([Errno 8] nodename nor servname provided, or not known)")': /pkgs/r/osx-arm64/repodata.json.zst

Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x10469a240>: Failed to resolve 'repo.anaconda.com' ([Errno 8] nodename nor servname provided, or not known)")': /pkgs/r/noarch/repodata.json.zst

Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x10456a8a0>: Failed to resolve 'repo.anaconda.com' ([Errno 8] nodename nor servname provided, or not known)")': /pkgs/main/osx-arm64/repodata.json.zst

Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x104621460>: Failed to resolve 'repo.anaconda.com' ([Errno 8] nodename nor servname provided, or not known)")': /pkgs/main/noarch/repodata.json.zst

failed

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.anaconda.com/pkgs/main/osx-arm64/repodata.json>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

If your current network has https://repo.anaconda.com blocked, please file
a support request with your network engineering team.

'https//repo.anaconda.com/pkgs/main/osx-arm64'



